(function(){
  'use strict';
  var fallbackActive=false;
  var searchedDraw=null;
  function byId(id){return document.getElementById(id);}
  function authHeaders(){var t=localStorage.getItem('bb_v34_token')||'';return {'Content-Type':'application/json','Authorization':'Bearer '+t,'X-Token':t};}
  async function api(url,opts){opts=opts||{};var r=await fetch(url,{method:opts.method||'GET',headers:authHeaders(),body:opts.body?JSON.stringify(opts.body):undefined,cache:'no-store'});var d=null;try{d=await r.json();}catch(e){}if(!r.ok)throw new Error((d&&((d.error&&d.error.message)||d.detail||d.message))||('요청 실패 '+r.status));return d;}
  function text(id,v){var el=byId(id);if(el)el.textContent=v;}
  function html(id,v){var el=byId(id);if(el)el.innerHTML=v;}
  function openPanel(tab,label){document.querySelectorAll('.panel').forEach(function(p){p.classList.toggle('active',p.id===tab);});document.querySelectorAll('button.nav[data-tab]').forEach(function(b){b.classList.toggle('active',b.dataset.tab===tab);});text('title',label||'BBLOTTO PRO');}
  function balls(nums){return (nums||[]).map(function(n){return '<span class="ball">'+Number(n)+'</span>';}).join(' ');}
  async function searchDraw(btn){var input=byId('drawSearchRound');var r=Number(input&&input.value||0);if(!r){alert('조회할 회차를 입력하세요.');return;}busy(btn,true,'조회 중...');try{var d=await api('/api/draws/search?round_no='+encodeURIComponent(r));searchedDraw=d&&d.ok?d:null;html('drawSearchResult',d&&d.ok?'<div class="draw-search-result"><b>'+d.round_no+'회</b><div class="nums-line">'+balls(d.numbers)+' <span class="bonus-ball">보너스 '+(d.bonus||'')+'</span></div><p>'+(d.message||'조회 완료')+'</p></div>':'<div class="draw-search-result warn"><p>'+((d&&d.message)||'조회 실패')+'</p></div>');}catch(e){html('drawSearchResult','<div class="draw-search-result warn"><p>'+e.message+'</p></div>');}finally{busy(btn,false);}}
  function applyDraw(){if(!searchedDraw||!searchedDraw.numbers||!searchedDraw.numbers.length){alert('먼저 회차 조회를 완료하세요.');return;}byId('checkRound').value=searchedDraw.round_no;byId('winningNums').value=searchedDraw.numbers.join(' ');byId('bonusNum').value=searchedDraw.bonus||'';text('autoRoundInfo',searchedDraw.round_no+'회 당첨번호를 적용했습니다.');}
  async function checkWinning(btn){var round=Number(byId('checkRound')&&byId('checkRound').value||0);if(!round){alert('회차를 입력하세요.');return;}busy(btn,true,'확인 중...');try{var d=await api('/api/check_winning',{method:'POST',body:{round_no:round,winning:byId('winningNums').value||'',bonus:Number(byId('bonusNum').value||0)}});if(d.wins&&d.wins.length){byId('winningNums').value=d.wins.join(' ');byId('bonusNum').value=d.bonus||'';}html('winningResult','<div class="hint"><b>'+round+'회 당첨확인 완료</b><br>처리 회원 '+((d.results&&d.results.length)||d.total_members||0)+'명</div>');}catch(e){alert(e.message);}finally{busy(btn,false);}}
  async function loadStats(btn,limit){busy(btn,true,'불러오는 중...');try{var d=await api('/api/stats?limit='+limit);var hot=(d.hot||[]).join(', ');var cold=(d.cold||[]).join(', ');html('statsBox','<div class="stats-dashboard"><div class="stats-kpi"><div class="stat-card"><b>'+(d.count||0)+'</b><span>분석 회차</span></div><div class="stat-card"><b>'+(d.sum_avg||'-')+'</b><span>평균 합계</span></div></div><div class="detail-section"><h4>HOT 번호</h4><p>'+hot+'</p><h4>COLD 번호</h4><p>'+cold+'</p></div></div>');}catch(e){alert(e.message);}finally{busy(btn,false);}}
  function busy(btn,on,label){if(!btn)return;if(on){btn.dataset.oldText=btn.textContent;btn.disabled=true;btn.textContent=label||'처리 중...';}else{btn.disabled=false;if(btn.dataset.oldText){btn.textContent=btn.dataset.oldText;delete btn.dataset.oldText;}}}
  function activate(){if(window.__bbBindingsReady)return;fallbackActive=true;document.documentElement.dataset.bblottoFallback='active';console.error('[STABLE-7] app.js 핵심 바인딩이 확인되지 않아 안전 버튼 모드를 활성화했습니다.');var badge=document.createElement('div');badge.id='stable5FallbackBadge';badge.textContent='STABLE-7 안전 버튼 모드';badge.style.cssText='position:fixed;right:12px;bottom:12px;z-index:99999;background:#7a1212;color:#fff;padding:8px 12px;border-radius:8px;font-size:12px';document.body.appendChild(badge);}
  document.addEventListener('click',function(e){if(!fallbackActive)return;var btn=e.target&&e.target.closest?e.target.closest('button'):null;if(!btn||btn.disabled)return;var nav=btn.matches('button.nav[data-tab]');if(nav){e.preventDefault();e.stopImmediatePropagation();openPanel(btn.dataset.tab,btn.textContent.trim());return;}if(btn.id==='searchDraw'){e.preventDefault();e.stopImmediatePropagation();searchDraw(btn);return;}if(btn.id==='applySearchedDraw'){e.preventDefault();e.stopImmediatePropagation();applyDraw();return;}if(btn.id==='checkWinning'||btn.id==='saveDraw'){e.preventDefault();e.stopImmediatePropagation();checkWinning(btn);return;}if(btn.classList.contains('statBtn')){e.preventDefault();e.stopImmediatePropagation();loadStats(btn,Number(btn.dataset.limit||0));return;}},true);
  function ready(){document.querySelectorAll('button').forEach(function(b){if(!b.hasAttribute('type'))b.type='button';});setTimeout(activate,1200);}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',ready,{once:true});else ready();
  window.BBLOTTO_CRITICAL_BUTTONS='STABLE-7.0';
})();
